### ISSUE TITLE
Ein Canvas auf dem man Malen kann.

### ISSUE THREAD

**Issue by Ahisi1** [Ahisi1/praktikum#5]
Ein Weißes Blatt auf dem man malen kann. Er soll in der Mitte sein, und er soll ungefähr 600px sein.
https://developer.mozilla.org/de/docs/Web/API/CanvasRenderingContext2D
Schaue https://codepen.io/georg-malahov/pen/QWeoKWq als Beispiel.

**Comment by georg-malahov** [comment]
@Ahisi1 
- Wie groß es sein soll?
- Finde gute **Beispiele**, wie man auf einem `<canvas />` malen kann.

Useful Links:
https://codepen.io/
https://webdesign.tutsplus.com/21-ridiculously-impressive-html5-canvas-experiments--net-14210a
