### ISSUE TITLE
Ein Farben Menu.

### ISSUE THREAD

**Issue by Ahisi1** [Ahisi1/praktikum#6]
Ein Kugel der Gradient aussieht. Er soll Rechts oben sein. Wenn man auf diesen Knopf drückt, öffnet sich ein Pop-Fenster, und
wo man aus Gradient Palette Farben auswählen kann.

**Comment by georg-malahov** [comment]
@Ahisi1 
- Was für ein Kugel? Wie soll er aussehen (Gradient)?
- Ist es ein Button mit Kugel icon/image?
- Was bedeutet "Auswählen"? Pop-Fenster? Aus Gradient Palette oder und vordefinierte Farben?

**Comment by Ahisi1** [comment]
#11
